---
title: "EFSA MUST-B data exploration"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The plan
Can we develop scenarios for BEEHAVE with the MUST-B / EFSA data, in combination with other available data. 

BEEHAVE needs:
 - Foraging hours per day, probably derived from radiation and temperatures in one-hour resolution.
 
## Foraging hours
@vicens1996 observed bees in Italy, and report minimum foraging temperatures of 12.5 °C and a minimum foraging radiation of 229 W/m² for April, but values in other months are even lower (min temp of 12 °C and  min radiation of approx. 160 W/m²) (see Fig. 4 within Vicens & Bosch). 
These values are used in the $get\_foraging\_hours$ function. 
TODO: decide which thresholds to use, and also wheter to include wind-speed and max temperature thresholds as well. 

## Useful links
Data description: 

https://www.efsa.europa.eu/en/supporting/pub/en-6695

Zenodo data repository: 

Data downloads from https://zenodo.org/record/4953762#.YYQmzJso_s2. 
Data provided as .csv mostly, saved in data/raw-data

Data exploration with shiny_app/app.R 
